import { AudioTrack } from './types';

export const audioTracksHE: AudioTrack[] = [
  {
    id: 'tide-of-stillness',
    title: '432 הרץ של שלווה פנימית',
    category: 'מדיטציה',
    description: 'צלילים עמוקים ב-432 הרץ לשלווה פנימית וריכוז שקט.',
    sourceType: 'local',
    localAssetId: 'tide-of-stillness',
    duration: 480,
    icon: 'musical-notes-outline',
    gradientColors: ['#A18CD1', '#FBC2EB'],
  },
  {
    id: 'drift-into-dusk',
    title: 'גלי לילה עדינים',
    category: 'שינה',
    description: 'גלים רכים של ערב שעוזרים למוח להאט ולהתכונן למנוחה.',
    sourceType: 'local',
    localAssetId: 'drift-into-dusk',
    duration: 469,
    icon: 'moon-outline',
    gradientColors: ['#2C3E50', '#4CA1AF'],
  },
  {
    id: 'pink-rainfall',
    title: 'יער הגשם הורוד',
    category: 'טבע',
    description: 'גשם של רעש ורוד חם לנוף קולי מרגיע ומקרקע.',
    sourceType: 'local',
    localAssetId: 'pink-rainfall',
    duration: 240,
    icon: 'rainy-outline',
    gradientColors: ['#FF9A9E', '#FECFEF'],
  },
  {
    id: 'pine-lullaby',
    title: 'רוגע ביער',
    category: 'טבע',
    description: 'אווירת יער עדינה שעוטפת אותך בשקט של הטבע.',
    sourceType: 'local',
    localAssetId: 'pine-lullaby',
    duration: 308,
    icon: 'leaf-outline',
    gradientColors: ['#43E97B', '#38F9D7'],
  },
  {
    id: 'lullaby-static',
    title: 'רעש ורוד עדין',
    category: 'ריכוז',
    description: 'רעש ורוד יציב שמסתיר הסחות ותומך בריכוז רגוע.',
    sourceType: 'local',
    localAssetId: 'lullaby-static',
    duration: 259,
    icon: 'radio-outline',
    gradientColors: ['#636E72', '#2D3436'],
  },
];

export default audioTracksHE;
