import { AudioTrack } from './types';

export const audioTracks: AudioTrack[] = [
  {
    id: 'rain-sounds',
    title: 'Gentle Rain',
    category: 'nature',
    description: 'Soft rainfall on a quiet evening. Let the steady rhythm wash away your stress.',
    sourceType: 'tts',
    ttsScript: 'Close your eyes and listen. Imagine you are sitting by a window, watching gentle rain fall on a quiet garden. Each drop dissolves a worry. Each drop brings peace. Simply breathe and listen to the rain.',
    duration: 300,
    icon: 'rainy-outline',
    gradientColors: ['#74B9FF', '#0984E3'],
  },
  {
    id: 'ocean-waves',
    title: 'Ocean Waves',
    category: 'nature',
    description: 'Rhythmic ocean waves crashing on a peaceful shore. The timeless sound of calm.',
    sourceType: 'tts',
    ttsScript: 'Picture yourself on a warm beach. The ocean stretches endlessly before you. Waves roll in... and recede. In... and out. Like your breath. Let the rhythm of the ocean become the rhythm of your breathing. You are at peace.',
    duration: 300,
    icon: 'water-outline',
    gradientColors: ['#2C3E50', '#4CA1AF'],
  },
  {
    id: 'forest-ambience',
    title: 'Forest Walk',
    category: 'nature',
    description: 'Birds singing, leaves rustling, a stream flowing through a sunlit forest.',
    sourceType: 'tts',
    ttsScript: 'You are walking through a beautiful forest. Tall trees surround you, their leaves filtering golden sunlight. Birds sing above. A gentle stream babbles nearby. The earth is soft under your feet. With each step, you feel more connected to nature, more grounded, more peaceful.',
    duration: 300,
    icon: 'leaf-outline',
    gradientColors: ['#43E97B', '#38F9D7'],
  },
  {
    id: 'meditation-bells',
    title: 'Tibetan Singing Bowls',
    category: 'meditation',
    description: 'The resonant tones of singing bowls that quiet the mind and open the heart.',
    sourceType: 'tts',
    ttsScript: 'Imagine the deep, resonant tone of a Tibetan singing bowl. The sound vibrates through the air, through your body. Each tone is an invitation to go deeper into stillness. Let the sound carry your thoughts away. All that remains is this moment. This breath. This peace.',
    duration: 300,
    icon: 'musical-notes-outline',
    gradientColors: ['#A18CD1', '#FBC2EB'],
  },
  {
    id: 'white-noise',
    title: 'White Noise',
    category: 'focus',
    description: 'Steady ambient noise that masks distractions and promotes deep focus or sleep.',
    sourceType: 'tts',
    ttsScript: 'Let your mind settle into a steady, gentle hum. Like the sound of air flowing softly. There is nothing to focus on. Nothing to think about. Just a constant, soothing presence that wraps around you like a warm blanket. Relax into the stillness.',
    duration: 300,
    icon: 'radio-outline',
    gradientColors: ['#636E72', '#2D3436'],
  },
  {
    id: 'body-scan-guided',
    title: 'Guided Body Scan',
    category: 'guided',
    description: 'A gentle voice guides you through a full body relaxation scan.',
    sourceType: 'tts',
    ttsScript: 'Lie down comfortably and close your eyes. We will journey through your body, releasing tension as we go. Start by bringing your attention to your feet. Notice any sensations. Now relax your feet completely. Move up to your calves. Notice and release. Your knees, your thighs, each releasing fully. Your hips and pelvis, letting go. Your stomach, rising and falling naturally. Your chest, open and free. Your hands, wrists, forearms, upper arms, all releasing. Your shoulders dropping away from your ears. Your neck, your jaw, your face, all softening. The top of your head, completely at ease. Your whole body is now deeply relaxed. Stay here as long as you need.',
    duration: 420,
    icon: 'body-outline',
    gradientColors: ['#667EEA', '#764BA2'],
  },
];

export default audioTracks;
