import { AudioTrack } from './types';

export const audioTracks: AudioTrack[] = [
  {
    id: 'tide-of-stillness',
    title: '432 Hz Inner Calm',
    category: 'meditation',
    description: 'Deep ambient tones tuned to 432 Hz for inner calm and quiet focus.',
    sourceType: 'local',
    localAssetId: 'tide-of-stillness',
    duration: 480,
    icon: 'musical-notes-outline',
    gradientColors: ['#A18CD1', '#FBC2EB'],
  },
  {
    id: 'drift-into-dusk',
    title: 'Gentle Night Waves',
    category: 'sleep',
    description: 'Soft evening waves that help the mind slow down and prepare for rest.',
    sourceType: 'local',
    localAssetId: 'drift-into-dusk',
    duration: 469,
    icon: 'moon-outline',
    gradientColors: ['#2C3E50', '#4CA1AF'],
  },
  {
    id: 'pink-rainfall',
    title: 'Pink Noise Rain',
    category: 'nature',
    description: 'Warm pink-noise rainfall for a cozy, grounding soundscape.',
    sourceType: 'local',
    localAssetId: 'pink-rainfall',
    duration: 240,
    icon: 'rainy-outline',
    gradientColors: ['#FF9A9E', '#FECFEF'],
  },
  {
    id: 'pine-lullaby',
    title: 'Woodland Calm',
    category: 'nature',
    description: 'Gentle forest ambience that wraps you in quiet woodland stillness.',
    sourceType: 'local',
    localAssetId: 'pine-lullaby',
    duration: 308,
    icon: 'leaf-outline',
    gradientColors: ['#43E97B', '#38F9D7'],
  },
  {
    id: 'lullaby-static',
    title: 'Gentle Pink Noise',
    category: 'focus',
    description: 'Steady pink noise that masks distractions and supports calm concentration.',
    sourceType: 'local',
    localAssetId: 'lullaby-static',
    duration: 259,
    icon: 'radio-outline',
    gradientColors: ['#636E72', '#2D3436'],
  },
];

export default audioTracks;
