import { BreathingExercise } from './types';

export const breathingExercisesHE: BreathingExercise[] = [
  {
    id: 'box-breathing',
    name: 'נשימת קופסה',
    description: 'טכניקה עוצמתית שמשמשת את חיל הים. שאיפה, עצירה, נשיפה ועצירה בזמנים שווים יוצרות קצב מרגיע.',
    duration: 240,
    rounds: 6,
    difficulty: 'beginner',
    benefits: ['מפחית מתח', 'משפר ריכוז', 'מוריד דופק', 'מרגיע חרדה'],
    gradientColors: ['#667EEA', '#764BA2'],
    icon: 'cube-outline',
    phases: [
      { type: 'inhale', duration: 4, instruction: 'שאף לאט דרך האף' },
      { type: 'hold', duration: 4, instruction: 'עצור את הנשימה בעדינות' },
      { type: 'exhale', duration: 4, instruction: 'נשוף לאט דרך הפה' },
      { type: 'hold', duration: 4, instruction: 'נוח והחזק ריק' },
    ],
  },
  {
    id: '4-7-8-breathing',
    name: 'נשימה מרגיעה 4-7-8',
    description: 'טכניקת ההרגעה הטבעית של ד"ר אנדרו וייל למערכת העצבים. אידיאלית להירדמות או הרגעת חרדה.',
    duration: 300,
    rounds: 5,
    difficulty: 'intermediate',
    benefits: ['מקדם שינה', 'מפחית חרדה', 'שולט בדחפים', 'מנהל תגובות רגשיות'],
    gradientColors: ['#43E97B', '#38F9D7'],
    icon: 'moon-outline',
    phases: [
      { type: 'inhale', duration: 4, instruction: 'שאף בשקט דרך האף' },
      { type: 'hold', duration: 7, instruction: 'החזק את הנשימה' },
      { type: 'exhale', duration: 8, instruction: 'נשוף לגמרי דרך הפה' },
    ],
  },
  {
    id: 'calm-breathing',
    name: 'נשימת הרגעה',
    description: 'נשימה פשוטה עם נשיפה מוארכת. נשיפות ארוכות מפעילות את מערכת העצבים הפאראסימפתטית להרגעת הגוף.',
    duration: 180,
    rounds: 6,
    difficulty: 'beginner',
    benefits: ['הרגעה מיידית', 'קל ללמוד', 'מפחית פאניקה', 'בטוח לכולם'],
    gradientColors: ['#A18CD1', '#FBC2EB'],
    icon: 'leaf-outline',
    phases: [
      { type: 'inhale', duration: 4, instruction: 'שאף דרך האף' },
      { type: 'exhale', duration: 6, instruction: 'נשוף לאט דרך הפה' },
    ],
  },
  {
    id: 'energizing-breath',
    name: 'נשימה מאנרגטת',
    description: 'נשימה קצבית מהירה להגברת אנרגיה וערנות. מצוינת כהתעוררות בוקר או ריסט אחר הצהריים.',
    duration: 120,
    rounds: 8,
    difficulty: 'intermediate',
    benefits: ['מגביר אנרגיה', 'משפר ערנות', 'מקדם זרימת דם', 'התעוררות בוקר'],
    gradientColors: ['#FD746C', '#FF9068'],
    icon: 'flash-outline',
    phases: [
      { type: 'inhale', duration: 2, instruction: 'שאיפה מהירה דרך האף' },
      { type: 'exhale', duration: 2, instruction: 'נשיפה חדה דרך הפה' },
      { type: 'rest', duration: 1, instruction: 'הפסקה קצרה' },
    ],
  },
  {
    id: 'anxiety-relief',
    name: 'נשימה להקלת חרדה',
    description: 'קצב עדין שנועד לעגן אותך ברגעי חרדה. התמקד בנשיפה הארוכה והאיטית לשחרור מתח.',
    duration: 300,
    rounds: 5,
    difficulty: 'beginner',
    benefits: ['מרגיע התקפי פאניקה', 'מעגן את התודעה', 'משחרר מתח שרירים', 'מאט מחשבות רצות'],
    gradientColors: ['#74B9FF', '#A29BFE'],
    icon: 'heart-outline',
    phases: [
      { type: 'inhale', duration: 5, instruction: 'מלא את הריאות לאט' },
      { type: 'hold', duration: 2, instruction: 'עצירה עדינה' },
      { type: 'exhale', duration: 7, instruction: 'שחרר את כל המתח עם הנשיפה' },
      { type: 'rest', duration: 1, instruction: 'הרשה לדממה' },
    ],
  },
];
