import { YogaSession } from './types';

export const yogaSessions: YogaSession[] = [
  {
    id: 'morning-stretch',
    title: 'Gentle Morning Stretch',
    description: 'Wake up your body with easy stretches anyone can do.',
    duration: 10,
    difficulty: 'beginner',
    gradientColors: ['#F5AF19', '#F12711'],
    icon: 'sunny-outline',
    youtubeId: 'g_tea8ZNtKc',
    poses: [
      { name: 'Mountain Pose', duration: 30, instruction: 'Stand tall, feet hip-width apart. Arms at your sides, palms facing forward. Root down through your feet and lengthen up through the crown of your head.', benefits: 'Improves posture and body awareness' },
      { name: 'Standing Forward Fold', duration: 45, instruction: 'Exhale and slowly fold forward from your hips. Let your head hang heavy. Bend your knees as much as you need. Sway gently side to side.', benefits: 'Stretches hamstrings and releases back tension' },
      { name: 'Cat-Cow Stretch', duration: 60, instruction: 'Come to all fours. Inhale, arch your back and look up (cow). Exhale, round your spine and tuck your chin (cat). Flow between these with your breath.', benefits: 'Warms the spine and relieves morning stiffness' },
      { name: 'Child\'s Pose', duration: 45, instruction: 'Sit back on your heels, arms extended forward on the mat. Rest your forehead down. Breathe deeply into your back body.', benefits: 'Calms the mind and stretches the back' },
      { name: 'Seated Side Stretch', duration: 60, instruction: 'Sit cross-legged. Reach your right arm up and over to the left. Feel the stretch along your right side. Hold, then switch sides.', benefits: 'Opens the side body and improves breathing' },
    ],
  },
  {
    id: 'anxiety-relief-yoga',
    title: 'Yoga for Anxiety Relief',
    description: 'Calming poses and breathwork to ease anxious feelings.',
    duration: 15,
    difficulty: 'beginner',
    gradientColors: ['#667EEA', '#764BA2'],
    icon: 'leaf-outline',
    youtubeId: 'hJbRpHZr_d0',
    poses: [
      { name: 'Easy Seated Pose', duration: 60, instruction: 'Sit comfortably with legs crossed. Close your eyes. Place hands on knees. Take 10 slow, deep breaths, counting each exhale.', benefits: 'Centers the mind and slows the heart rate' },
      { name: 'Standing Forward Fold', duration: 45, instruction: 'Stand and fold forward gently. Let gravity pull tension from your head and neck. Grab opposite elbows and sway.', benefits: 'Calms the nervous system' },
      { name: 'Legs Up The Wall', duration: 120, instruction: 'Lie on your back with your legs resting up against a wall. Arms out to the sides, palms up. Close your eyes and breathe deeply.', benefits: 'Activates the parasympathetic nervous system' },
      { name: 'Supine Twist', duration: 60, instruction: 'Lying on your back, hug your knees to your chest, then let both knees fall to the right. Extend arms out. Look left. Hold, then switch.', benefits: 'Releases stored tension in the spine' },
      { name: 'Savasana', duration: 120, instruction: 'Lie flat on your back, arms at your sides, palms up. Close your eyes. Release all effort. Let the floor hold you completely.', benefits: 'Deep relaxation and integration of practice' },
    ],
  },
  {
    id: 'desk-stretches',
    title: 'Desk Break Stretches',
    description: 'Quick stretches you can do at your desk to relieve work tension.',
    duration: 5,
    difficulty: 'beginner',
    gradientColors: ['#43E97B', '#38F9D7'],
    icon: 'desktop-outline',
    poses: [
      { name: 'Neck Rolls', duration: 30, instruction: 'Drop your chin to your chest. Slowly roll your head to the right, back, left, and forward. Repeat 3 times each direction.', benefits: 'Releases neck tension from screen time' },
      { name: 'Seated Cat-Cow', duration: 30, instruction: 'Sitting in your chair, place hands on knees. Inhale and arch your back. Exhale and round your spine. Repeat 8 times.', benefits: 'Relieves lower back stiffness' },
      { name: 'Shoulder Shrugs', duration: 20, instruction: 'Inhale, raise your shoulders to your ears. Hold for 2 seconds. Exhale, drop them. Repeat 5 times.', benefits: 'Releases shoulder tension' },
      { name: 'Seated Twist', duration: 30, instruction: 'Sit tall. Place your right hand on your left knee, left hand behind you. Twist gently to the left. Hold 5 breaths. Switch sides.', benefits: 'Improves spinal mobility' },
      { name: 'Wrist Circles', duration: 20, instruction: 'Extend your arms. Make circles with your wrists, 10 times each direction. Then shake your hands out loosely.', benefits: 'Prevents repetitive strain' },
    ],
  },
  {
    id: 'bedtime-yoga',
    title: 'Bedtime Yoga',
    description: 'Wind down with slow, soothing poses to prepare for sleep.',
    duration: 12,
    difficulty: 'beginner',
    gradientColors: ['#2C3E50', '#4CA1AF'],
    icon: 'moon-outline',
    youtubeId: 'v7AYKMP6rOE',
    poses: [
      { name: 'Child\'s Pose', duration: 90, instruction: 'Kneel and fold forward, arms extended. Rest your forehead on the mat. Breathe slowly and deeply for 10 breaths.', benefits: 'Calms the mind for sleep' },
      { name: 'Reclined Butterfly', duration: 90, instruction: 'Lie on your back. Bring the soles of your feet together, knees falling open. Place one hand on your heart, one on your belly.', benefits: 'Opens hips and promotes deep relaxation' },
      { name: 'Happy Baby', duration: 60, instruction: 'On your back, grab the outsides of your feet with your knees wide. Gently rock side to side like a happy baby.', benefits: 'Releases lower back and hip tension' },
      { name: 'Supine Twist', duration: 90, instruction: 'Hug your knees in, then let them fall to the right. Open your arms wide. Close your eyes. 8 breaths each side.', benefits: 'Wrings out the day\'s tension' },
      { name: 'Savasana', duration: 180, instruction: 'Lie flat. Cover yourself with a blanket if you wish. Completely let go. There is nothing left to do today.', benefits: 'Prepares the body and mind for deep sleep' },
    ],
  },
  {
    id: 'strength-flow',
    title: 'Strength & Balance Flow',
    description: 'Build inner and outer strength with grounding standing poses.',
    duration: 20,
    difficulty: 'intermediate',
    gradientColors: ['#FA709A', '#FEE140'],
    icon: 'fitness-outline',
    youtubeId: 'oBu-pQG6akg',
    poses: [
      { name: 'Sun Salutation A', duration: 120, instruction: 'Mountain pose → forward fold → halfway lift → plank → chaturanga → upward dog → downward dog. Repeat 3 rounds, flowing with breath.', benefits: 'Full-body warm-up and energy boost' },
      { name: 'Warrior I', duration: 60, instruction: 'Step right foot forward, bend the knee to 90 degrees. Back foot at 45 degrees. Raise arms overhead. Gaze up. 5 breaths each side.', benefits: 'Builds leg strength and confidence' },
      { name: 'Warrior II', duration: 60, instruction: 'From Warrior I, open your hips and arms to the side. Front knee over ankle. Gaze past your front fingertips. Strong and steady.', benefits: 'Strengthens legs and improves stamina' },
      { name: 'Tree Pose', duration: 60, instruction: 'Stand on your left foot. Place right foot on inner thigh or calf (not knee). Hands at heart center or overhead. Find a focus point. Each side.', benefits: 'Improves balance and concentration' },
      { name: 'Bridge Pose', duration: 60, instruction: 'Lie on back, knees bent, feet hip-width apart. Press feet down and lift hips. Clasp hands under your back. Hold for 8 breaths.', benefits: 'Strengthens back and opens chest' },
    ],
  },
];

export default yogaSessions;
